version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: PasswordManagerDb
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPassword
      PGDATA: /var/lib/postgresql/data
